version: '3.8'

services:
  hunyuan3d-21:
    build:
      context: .
      cache_from:
        - hunyuan3d-21:builder
        - hunyuan3d-21:latest
    image: hunyuan3d-21:latest
    container_name: hunyuan3d-21-dev
    ports:
      - "8080:8080"
    environment:
      - HY3DGEN_MODELS=/app/weights
      - PYOPENGL_PLATFORM=egl
      - CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID}
      - CLOUDFLARE_ACCESS_KEY_ID=${CLOUDFLARE_ACCESS_KEY_ID}
      - CLOUDFLARE_SECRET_ACCESS_KEY=${CLOUDFLARE_SECRET_ACCESS_KEY}
      - CLOUDFLARE_BUCKET_NAME=${CLOUDFLARE_BUCKET_NAME:-hunyuan3d}
      - CLOUDFLARE_ACCOUNT_HASH=${CLOUDFLARE_ACCOUNT_HASH}
    volumes:
      - model_cache:/app/weights
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  model_cache: